#######################################################################################
# A default configuration that will be loaded for all jupyter books
# See the documentation for help and more options: 
# https://jupyterbook.org/customize/config.html

#######################################################################################
# Book settings
title                       : Introduction to Operating Systems # The title of the book. Will be placed in the left navbar.
author                      : Angela Demke Brown, Orran Krieger & Larry Woodman  # The author of the book
copyright                   : "2022"  # Copyright year to be placed in the footer
logo                        : logo.png  # A path to the book logo
only_build_toc_files        : true

# Add a bibtex file so that we can create citations
bibtex_bibfiles:
  - references.bib


html:
  use_repository_button: true
  use_edit_page_button: true
  use_issues_button: true
  comments:
    hypothesis: true
#    utterances:
#      repo: "okrieg/openos"
      
#######################################################################################
# Launch button settings
launch_buttons:
  # open textbook pages in lab to provide desktop env
  binderhub_url             : https://mybinder.org  # The URL of the BinderHub (e.g., https://mybinder.org)
  notebook_interface        : jupyterlab  # The interface interactive links will activate ["classic", "jupyterlab"]
  # binderhub_url: "" # trying to remove binder
  # launch on the public RedHat Operate First Service
  jupyterhub_url: "https://jupyterhub-opf-jupyterhub.apps.smaug.na.operate-first.cloud"
  # launch on the private BU service -- use this for BU courses -- students must be authorized  
  # jupyterhub_url: "https://jupyterhub-redhat-ods-applications.apps.buaws-dev.idu6.p1.openshiftapps.com"

repository:
  url                       : https://github.com/okrieg/openos  # The URL to your book's repository
  path_to_book              : "content"  # A path to your book's folder, relative to the repository root.
  branch                    : "main"  # Which branch of the repository should be used when creating links
###############################

parse:
  # see https://jupyterbook.org/customize/config.html
  # don't forget to list any other extensions you want enabled,
  # including those that are enabled by default!
  myst_enable_extensions:
    - html_image
    - amsmath
    - colon_fence
    - dollarmath
    - linkify
    - substitution
    - html_admonition

execute:
  execute_notebooks: "cache"
  allow_error: true
